# Generated by Django 3.0.5 on 2020-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=100)),
                ('fantasia', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('codigo_regime_tributario', models.CharField(max_length=1)),
                ('regime_especial_de_tributacao', models.CharField(max_length=1)),
                ('cnae', models.CharField(max_length=7)),
                ('inscricao_municipal', models.CharField(max_length=10)),
                ('inscricao_estadual', models.CharField(max_length=10)),
                ('identificacao_csc', models.CharField(max_length=5)),
                ('codigo_contribuinte', models.CharField(max_length=50)),
            ],
        ),
    ]
