# Generated by Django 3.0.5 on 2020-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
